name: Execute Reusable Workflow
description: 'Ein Workflow, der eine wiederverwendbare Workflow-Datei aufruft'
    # Wenn anderes repo: USER_OR_ORG_NAME/REPO_NAME/.github/workflows/REUSABLE_WORKFLOW_FILE.yml@TAG_OR_BRANCH
    # Wenn lokal: ./.github/workflows/REUSABLE_WORKFLOW_FILE.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nestedjob:
    uses: ./.github/workflows/reusable_workflow.yml
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      environment: 'production'
      path: '.'
