name: Reusable Build Workflow
on:
  workflow_call:  # Triggers the workflow when called by another workflow
    inputs:
      path:
        description: 'Der Pfad, der für den Build verwendet werden soll'
        required: true
        default: '.'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installiere Abhängigkeiten
        run: echo "npm install mit Pfad ${{ inputs.path }}"


