name: Reusable Workflow Example

on:

  workflow_call:  # Triggers the workflow when called by another workflow
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
        default: 'staging'
      path:
        description: 'Der Pfad, der für den Build und Test verwendet werden soll'
        required: true
        type: string
        default: '.'
    secrets:
      personal_access_token:
        required: true

jobs:

  build:
    uses: ./.github/workflows/build_workflow.yml
    with:
      path: ${{ inputs.path }}
  
  test:
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/test_workflow.yml
    with:
      path: ${{ inputs.path }}
  
  test_output:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{ needs.test.outputs.result }}

  deploy:
    needs: [build, test]
    uses: ./.github/workflows/deploy_workflow.yml
    secrets: inherit # Gibt alle Secrets an den aufgerufenen Workflow weiter
    with:
      environment: ${{ inputs.environment }}