name: Test My Action

on:
  push:
    branches:
    - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Example Action
        uses: ./.github/actions/example-action
        with:
          my-input: 'GitHub'